name: Email Step Workflow

on:
  push:
    branches:
      - main       

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 23f2003814@ds.study.iitm.ac.in
        run: echo "Hello, world!"
