name: Cache dependencies

on:
  push:
    branches:
      - main          # runs on pushes to main branch
  workflow_dispatch:  # allows manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache dependencies
        id: cache-step
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip                      # example caching pip packages
          key: cache-8a2462e                      # your fixed cache key
          restore-keys: |
            cache-8a2462e

      - name: prime-cache-8a2462e
        run: echo "Cache hit: ${{ steps.cache-step.outputs.cache-hit }}"
