name: Daily Commit

on:
  schedule:
    # Runs daily at 2:30 AM UTC (adjust hours/minutes as required)
    - cron: '37 16 * * *'

jobs:
  daily-commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Update file - 23f2003814@ds.study.iitm.ac.in
      run: |
        echo "Daily automated update - $(date)" >> daily-update.txt

    - name: Commit changes
      run: |
        git config --global user.email "23f2003814@ds.study.iitm.ac.in"
        git config --global user.name "GitHub Actions Bot"
        
        git add daily-update.txt
        git commit -m "Automated daily commit [23f2003814@ds.study.iitm.ac.in]" || echo "No changes to commit"
        
        git push origin HEAD:${{ github.ref }}
