name: Email Step Workflow - 23f2003814@ds.study.iitm.ac.in

on:
  push:
    branches:
      - main       # Or your main branch name to trigger on pushes

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 23f2003814@ds.study.iitm.ac.in
        run: echo "Hello, world!"
